services:
  web-server:
    build: .
    ports:
      - 8080:8080
    container_name: express_app

  watchtower: 
    image: nickfedor/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower